### ISSUE TITLE
PBS - Proxmox Backup Server

### ISSUE THREAD

**Issue by oliv63** [Weilbyte/PVEDiscordDark#53] opened 2021-01-11 16:54 UTC
Hello,
Sorry for maybe wrong channel, but I would like to thank you for your **Great job** on PVEDiscordDark theme 🥇 
It works like a charm 👍 
Is there any chance to see your python script adapted for PBS one day ? it would be wonderfull !

I really hope that your work will be adopted by proxmox team for further release

**Comment by ArnoCtr** [comment] 2021-01-12 14:14
+1

**Comment by Weilbyte** [comment] 2021-01-13 11:14
Thank you!

This seems to be a duplicate of #44, so you might find your answer there. 
As for PMG, I will take a look at it some other day and see how much there is to do with it.

**Closed by Weilbyte** 2021-01-13 11:14 UTC
