### ISSUE TITLE
Syntax issue on line 45

### ISSUE THREAD

**Issue by techano** [Weilbyte/PVEDiscordDark#26] opened 2020-08-30 05:06 UTC
Command issued: python3 PVEDiscordDark.py
Error received:
![image](https://user-images.githubusercontent.com/20607160/91651638-e726a780-ea43-11ea-934b-8eaff2f22ff7.png)
Proxmox version: 5.3-8

**Comment by jonasled** [comment] 2020-08-30 08:50
Are there more details below, because I can't reproduce the error

**Comment by jonasled** [comment] 2020-08-30 08:51
And can you please poste your Python Version (`python3 --version`)

**Comment by zimmertr** [comment] 2020-08-30 23:28
Install successfully worked for me using the script [here](https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.py) and `python3 /tmp/PVEDiscordDark.py --action install`

```bash
root@earth:~# pveversion
pve-manager/6.2-4/9824574a (running kernel: 5.4.34-1-pve)

root@earth:~# python3 --version
Python 3.7.3
```

**Comment by Weilbyte** [comment] 2020-08-31 00:15
Are you using the latest script? If so then please provide Python3 version.

**Comment by techano** [comment] 2020-08-31 03:40
I made this issue in regards to another person who was having the issue and they will be responding to your questions regarding their issue.

**Comment by CCTrollz** [comment] 2020-08-31 03:43
Apologies for the wait.
```cart@cerberus:~$ python3 --version
Python 3.8.2```

**Comment by jonasled** [comment] 2020-08-31 07:58
It looks like your python version is to old, can you please upgrade to a version newer than 3.6

**Comment by jonasled** [comment] 2020-08-31 08:19
I've made some changes to the installer script which also should fix the problem.

**Comment by Weilbyte** [comment] 2020-08-31 14:44
Merged.

**Comment by Weilbyte** [comment] 2020-08-31 17:03
Reopening as https://github.com/Weilbyte/PVEDiscordDark/blob/master/PVEDiscordDark.py#L91 uses fstrings (will solve a bit later).

**Closed** 2020-09-21 23:59 UTC
Labels: Kind: Bug 🐛, Priority: Low, Status: Assigned
