### ISSUE TITLE
Usabillity bug

### ISSUE THREAD

**Issue by alex050478** [Weilbyte/PVEDiscordDark#55] opened 2021-01-15 21:32 UTC
When selecting a VM on the left in Server View, without dark mode there is a nice background that shows what vm you are working on. With Dark mode installed,  there seems to have been replaced with a blue border. The thing is that the border disappears when cliking in another frame.  

See screenshot. When I click in red circle, the blue box goes away. The problem is that I was changing stuff on the wrong VM because of this. Without dark mode this would not have happened (just tested it) because the background stays.  

Love this dark mode though! Hope this helps. 

![Screenshot 2021-01-15 232509](https://user-images.githubusercontent.com/33238936/104780581-5433a300-5781-11eb-8522-128fa633360c.jpg)

**Comment by Weilbyte** [comment] 2021-01-16 01:36
Sorry that you've accidentally edited the wrong VM because of this. 

I can see what you are talking about. The blue outline is not meant to last after a click, but I will change the selected color to be the same as the hover color so it will look like this: 
![image](https://user-images.githubusercontent.com/43392677/104793561-7807e080-57a3-11eb-858f-98b6e45f3b02.png)

This would be a better indicator of the selected resource I think.

**Comment by alex050478** [comment] 2021-01-16 07:10
No need to be sorry, glad to be of help! Sounds like a good solution. Thanks.

**Comment by RisedSky** [comment] 2021-01-18 10:50
Can reproduce this, i also agree with this 🔽 

> 
> 
> Sorry that you've accidentally edited the wrong VM because of this.
> 
> I can see what you are talking about. The blue outline is not meant to last after a click, but I will change the selected color to be the same as the hover color so it will look like this:
> ![image](https://user-images.githubusercontent.com/43392677/104793561-7807e080-57a3-11eb-858f-98b6e45f3b02.png)
> 
> This would be a better indicator of the selected resource I think.

**Comment by Weilbyte** [comment] 2021-01-18 17:41
Will be fixed tomorrow.

**Closed** 2021-01-20 16:58 UTC
Labels: Kind: Bug 🐛, Priority: Low, Status: In Progress

**Comment by Weilbyte** [comment] 2021-01-20 16:59
A bit longer than "tomorrow", my bad, but its fixed.
